spring.application.name=CoffeeShopIMS

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/coffeeshop_inventory}

spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:coffeeshopims}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:change-me-to-256-bit-random-string!!}
jwt.expiration-ms=86400000

springdoc.show-javadoc.enabled=true